apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-dep
  labels:
    created_by: naveenrajoli
    project: database
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: database
      app: mysql
      tier: database
  template:
    metadata:
      name: mysql-pod
      labels:
        project: database
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image:
        ports:
        - containerPort: 3306

--- 

apiVersion: v1
kind: Service
spec:
  selector:
    project: database
    app: mysql
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306