apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: expense-project
  name: backend-dep
  labels:
    created_by: naveenrajoli
    project: expense
    app: backend
    tier: database-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: database-tier
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
        tier: database-tier
    spec:
      containers:
      - name: backend
        image: naveenrajoli/2025backend:1.0.0 
        ports:
        - containerPort: 8080

--- 

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expense-project
spec:
  selector:
    app: backend
    tier: database-tier
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080