apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: expense-project
  name: backend-dep
  labels:
    created_by: naveenrajoli
    project: database
    app: backend
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: database
      app: backend
      tier: database
  template:
    metadata:
      name: backend-pod
      labels:
        project: database
        app: backend
        tier: database
    spec:
      containers:
      - name: backend
        image: naveenrajoli/2025backend:1.0.0 
        ports:
        - containerPort: 3306

--- 

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expense-project
spec:
  selector:
    project: database
    app: backend
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306